### ISSUE TITLE
Cómo puedo generar un documento de abono del cliente

### ISSUE THREAD

**Issue by mokshasoftware** [AndresRamos/ARSoftware.Contpaqi.Comercial#11]
Hola buenas tardes, actualmente utilizo tu librería para generar una facturación automática, el resultado es excelente, y después de revisar el código, puedo generar facturas masivas sin problema.
Ahora me veo en la necesidad de generar notas de crédito para dichas facturas, el problema es que el documento que tengo que generar es uno llamado "Abonos del Cliente" (que es el que toman en la empresa como Nota de Crédito), sin embargo no he encontrado ninguna referencia de cómo crear este documento desde el SDK.
Hasta ahora el esquema que seguía era el siguiente:

- Creo el documento
- Entre otros parámetros, asigno el id de concepto (en este caso para la empresa que trabajo es el 690 que tiene su plantilla basada en Nota de Crédito)
- Doy de alta el documento
- A continuación agrego "n" movimientos
  - Asigno el código de almacén al movimiento
  - Indico si afecta o no
  - Indico el código de producto
  - Doy de alta el movimiento en el documento

Sin embargo, en el documento de nota de crédito (o abono al cliente llamado "Descuentos Varios"), no hay dónde agregar un movimiento, sólo calcula el neto, el iva y listo...

Mi pregunta es, si esto se puede hacer desde el SDK, y si es así, hay algún lugar donde pueda revisar el esquema a seguir? 
Entiendo que la cosa va por el lado de crear un documento de tipo documentoAbonoCargo, pero hasta ahí llego.
Veo que la función sdkComercial.fAltaDocumentoAbonoCargo requiere un documento de tipo tDocumento, entonces en mi teoría realizo lo siguiente:

- Creo un documento de tipo tDocumento
- Cómo indico que este tDocumento es un abono?
- Veo que tiene para poner un campo de tipo aDescuentoDoc1 y aDescuentoDoc2 aún no intenté poner valores ahí, pero voy a ver qué pasa
- Veo también que hay un campo aImporte, debería poner ahí el importe total? en fin

Agradecería mucho cualquier orientación, ya que desconozco todo de contpaq y lo que he logrado ha sido gracias a tu librería, tal vez puedas ayudarme un poco en como completar este paso mientras sigo haciendo pruebas. 

Muchas gracias desde ya

**Comment by mokshasoftware** [comment]
De hecho ahora intenté crear un documento abono / cargo, moviendo a los valores de importe y descuento, pero me arroja un código de error 130246, que lo he buscado por todo Google sin mayor éxito... 

![image](https://user-images.githubusercontent.com/48501260/68253693-2df76c80-ffee-11e9-82af-5e4c0d4eca44.png)

**Comment by Jebux01** [comment]
Hola @mokshasoftware lograste hacer funcionar tu app ? yo estoy en la misma, necesito generar los documentos que se agregen a facturas pendientes por pagar

**Comment by mokshasoftware** [comment]
Hola! Al final no le seguí, porque el proyecto se suspendió por lo de la pandemia, pero en aquel entonces, contacté al desarrollador de la clase y estuvo dispuesto a ayudarme, de hecho había llegado a hacer una clase de muestra, pero ya no tuve contacto con él, y ya no pude verlo, creo que lo ubiqué a través de Facebook (rastreando su cuenta de github) y sin problema me ayudó, ahora no tengo nada de información al respecto, sino con gusto la compartía contigo

 

Saludos!

**Comment by AndresRamos** [comment]
Ya agregue un [proyecto de ejemplos](https://github.com/AndresRamos/Contpaqi/tree/master/Contpaqi.Sdk.Ejemplos) del SDK. Muy pronto estaré agregando un ejemplo de como generar este tipo de documentos. Cuando este listo les dejare saber con otro comentario.

**Comment by CarlosCeballosRM** [comment]
Se puede crear cualquier tipo de documento lo único que cambiará es crear el documento con el concepto deseado

**Comment by Jebux01** [comment]
@mokshasoftware yo de nuevo, tendras un ejemplo de la facturacion automatica? me he quedado con la intriga

**Comment by AndresRamos** [comment]
En el Wiki tengo un ejemplo de como [Crear documento de cargo o abono](https://github.com/AndresRamos/ARSoftware.Contpaqi.Comercial/wiki/Documentos#crear-documento-de-cargo-o-abono).

Tambien en el proyecto de ejemplos hay un ejemplo.
