### ISSUE TITLE
Usuario y contraseña al abrir empresa

### ISSUE THREAD

**Issue by hdz1javier2** [AndresRamos/ARSoftware.Contpaqi.Comercial#18]
Hola, en Comercial cada vez que se invoca la apertura de una empresa, se abre una ventana para capturar usuario-contraseña. ¿Hay manera de predefinir esto en el código o de evitar que lo solicite? Mi intención es automatizar la ejecución de mi programa y esta situación lo hace imposible.

**Comment by ErickCastellanos** [comment]
@hdz1javier2 Revisa las funciones fInicioSesion y/o fInicioSesionSDKCONTPAQi. Posiblemente esas funciones te ayudarán con tu problema.

**Comment by AndresRamos** [comment]
En el Wiki [Inicializar y finalizar SDK](https://github.com/AndresRamos/ARSoftware.Contpaqi.Comercial/wiki/Inicializar-y-finalizar-SDK) podras encontrar documentación de las diferentes maneras que se puede inicializar el SDK.
Si no quieres que se abra la ventana debes [Inicializar SDK Con Parámetros](https://github.com/AndresRamos/ARSoftware.Contpaqi.Comercial/wiki/Inicializar-y-finalizar-SDK#inicializar-sdk-con-par%C3%A1metros)
```csharp
public static int InicializarSdk(string usuario, string password)
{
    SetCurrentDirectory();
    ComercialSdk.fInicioSesionSDK(usuario, password);
    return ComercialSdk.fSetNombrePAQ(NombrePaqComercial);
}
```
