### ISSUE TITLE
Error al cancelar documento

### ISSUE THREAD

**Issue by hdz1javier2** [AndresRamos/ARSoftware.Contpaqi.Comercial#19]
Hola, estoy intentando, tanto con AdminPAQ como con Comercial, cancelar un documento de venta y la función me regresa un error 130237. En el catálogo de errores que tengo no hay una descripción asociada a esta clave de error y la función fError no regresa ninguna descripción del problema. 
Esta es la función que estoy usando:
`ComercialSdk.fCancelaDocumento();`

Les agradezco su ayuda para entender la causa de esta falla

**Comment by CarlosCeballosRM** [comment]
int a = ComercialSdk.fCancelaDocumento();

                                   if (a == 0)
                                    {
                                        Console.WriteLine("Cuenta guardada");
                                    }
                                    else {
                                     rError(a);
                                    }

public static void rError(int iError)
        {
            StringBuilder sMensaje = new StringBuilder(512);

            if (iError != 0)
            {
                ComercialSdk.fError(iError, sMensaje, 512);
                Error = "Error: " + sMensaje;
                Console.WriteLine(Error);
            }
        }

con esto debe devolverte el error

**Comment by AndresRamos** [comment]
En el Wiki podras encontrar la pagina [Cancelar Documento](https://github.com/AndresRamos/ARSoftware.Contpaqi.Comercial/wiki/Cancelar-documento).
Ahi tengo un ejemplo de como cancelar un documento en Comercial.
```csharp
/// <summary>
/// Cancelar un documento.
/// </summary>
/// <param name="idDocumento">El id del documento a cancelar.</param>
/// <param name="contrasenaCertificado">La contrasena del certificado.</param>
/// <param name="motivoCancelacion">El codigo de motivo de cancelacion.</param>
/// <param name="uuidRemplazo">El UUID de reemplazo si se requiere.</param>
public static void CancelarDocumento(int idDocumento, string contrasenaCertificado, string motivoCancelacion, string uuidRemplazo)
{
    // Buscar el documento
    ComercialSdk.fBuscarIdDocumento(idDocumento).TirarSiEsError();

    // Ingregar la contrasena del certificado
    ComercialSdk.fCancelaDoctoInfo(contrasenaCertificado).TirarSiEsError();

    // Cancelar el documento
    ComercialSdk.fCancelaDocumentoConMotivo(motivoCancelacion, uuidRemplazo).TirarSiEsError();
}
```
