### ISSUE TITLE
ERROR alta documento

### ISSUE THREAD

**Issue by preguntando2** [AndresRamos/ARSoftware.Contpaqi.Comercial#21]
al dar de alta documentos, aveces el programa se traba , pareciera que está trabajando pero deja de hacerlo, solo que No marca error o finaliza el programa, solo sigue corriendo.

 agradecería cualquier sugerencia.

**Comment by mariolugo2** [comment]
Puedes dar un ejemplo de como creas tú documento.

**Comment by mariolugo2** [comment]
> al dar de alta documentos, aveces el programa se traba , pareciera que está trabajando pero deja de hacerlo, solo que No marca error o finaliza el programa, solo sigue corriendo.
> 
> agradecería cualquier sugerencia.

Revisa que tengas los permisos necesarios en los folder de instalación y ruta de empresas así como permisos de administrador y compatibilidad al ejecutable del desarrollo.
