### ISSUE TITLE
Alta de Documento de Proveedor

### ISSUE THREAD

**Issue by CarlosSaldivarTorres** [AndresRamos/ARSoftware.Contpaqi.Comercial#23]
Buenas tardes,
Estoy creando por medio de SDK documentos en contpaq comercial (con .net),  para facturas de cliente no tengo problemas las he creado, timbrado, etc.  Pero para crear documentos para proveedores no logro encontrar en la documentacion del SDK que parametro o campo es el que le debo de capturar para indicarle que es factura de proveedor. 
Me podran apoyar?

Gracias!

**Comment by CarlosCeballosRM** [comment]
Al registrar un nuevo con fAltaCteProv , cTipoCliente  = 3 que es proovedor,
al crear el documento asígnalo hacia ese cliente y creo que con eso resuelves tu problema

**Comment by AndresRamos** [comment]
El proceso para crear un documento para cliente o proveedor es igual, solamente cambia el cliente/proveedor. Como comenta Carlos, es posible que el proveedor que estas asignando al documento solamente es tipo cliente.
