### ISSUE TITLE
Nuevas funciones fAltaCuentaBancaria,  funciones carta porte

### ISSUE THREAD

**Issue by TheHelix09** [AndresRamos/ARSoftware.Contpaqi.Comercial#25]
Que tal, tengo la duda de cuando y como se pueden implementar esas nuevas funciones , saludos

**Comment by AndresRamos** [comment]
Al parecer existen varias funciones para trabajar con cuentas bancarias en Comercial.
- fAltaCuentaBancariaEmpresa
- fAltaCuentaBancariaCliente
- fModificaCuentaBancariaEmpresa
- fModificaCuentaBancariaCliente
- fBorraCuentaBancariaEmpresa
- fBorraCuentaBancariaCliente
- fCuentaBancariaEmpresaDoctos

Voy a agregarlas en la siguiente version y agregar ejemplos en wiki y en los proyectos de ejemplo.

Referente a la carta porte, se debe crear un archivo ".ini" con los datos de la carta porte y pasar la ruta de este archivo al parametro aArchivoAdicional en la funcion fEmitirDocumento.
