### ISSUE TITLE
Malware en archivo de descarga favor de revisar

### ISSUE THREAD

**Issue by Githubiano** [AndresRamos/ARSoftware.Contpaqi.Comercial#26]
Si puedes revisar los archivos de descarga, me lanza una alerta de Malware te envío la captura:

Malware: Win32:Evo-gen en Contapaqi.Sdk.Ejemplos.exe
https://snipboard.io/S8Ck1Z.jpg
Me interesa el proyecto espero poder aportar

Saludo
![Error de Infeccion en paquete](https://user-images.githubusercontent.com/11299336/139007882-f597dbf6-709e-4009-a97a-e29d1d1df8ac.png)
s

**Comment by AndresRamos** [comment]
Los ejecutables no está firmados y no tiene certificado por lo que es común que cuando lo descargas y ejecutas el antivirus te notifique. En cuento a malware creo que tú mismo puedes ver el código fuente y validarlo.
