### ISSUE TITLE
No puedo Iniciar session

### ISSUE THREAD

**Issue by elmasfreg** [AndresRamos/ARSoftware.Contpaqi.Comercial#27]
![image](https://user-images.githubusercontent.com/42079475/149016241-cfb1768e-cc4f-4887-8d5e-7806ab7099b7.png)
![image](https://user-images.githubusercontent.com/42079475/149016290-69c9560c-2acf-4881-8edd-8669ab9c6b13.png)
Al iniciar session me marca los siguientes errores y no me deja seguir

**Comment by pstoneTI** [comment]
¿Estas ejecutando la aplicación en modo administrador?

**Comment by elmasfreg** [comment]
si ya pude resolver ejecute administrador visual studio y funciono tengo
una duda mas para Hacer una compra o generar una compra en que parte del
sistema se realiza?[image: image.png]

**Comment by AndresRamos** [comment]
En el Wiki podras encontrar [Documentos](https://github.com/AndresRamos/ARSoftware.Contpaqi.Comercial/wiki/Documentos) de cómo crear documentos.
Tambien en el proyecto de ejemplos hay ejemplos de cómo crear documentos de compras.
