### ISSUE TITLE
Como se podria Generarl Una Compra?

### ISSUE THREAD

**Issue by elmasfreg** [AndresRamos/ARSoftware.Contpaqi.Comercial#28]
hola que tal como estan buenas tardes, muchas gracais por esta gran contriobucion me gustaria saber como genenerar una comprar debido a que este te pide un Id de Documento mi duda es es un Id Aleatorio?
![image](https://user-images.githubusercontent.com/42079475/149022731-a79a14b3-221c-4898-a7d2-87a6a391c499.png)
mi duda es sobre al momento de asignar un Id que es lo que generar esto 
![image](https://user-images.githubusercontent.com/42079475/149023067-c8a3247b-97fc-4185-86ff-b73742cffe58.png)
 es algun id aleatorio o se puede realizar mediante el sdk?

**Comment by marc2684** [comment]
@elmasfreg el proceso es crear el documento mediante el sdk, el cual te retorna el ID a utilizar en tus operaciones subsecuentes.

**Comment by AndresRamos** [comment]
En el wiki podras encontrar la pagina [Documentos](https://github.com/AndresRamos/ARSoftware.Contpaqi.Comercial/wiki/Documentos) con documentacion de como crear un documento de tipo compra.
Todos los documentos se crean de la misma manera, como para facturas, en compras simplemente debe ser a un cliente de tipo proveedor.
Tambien podras encontrar ejemplos en los proyectos de ejemplos. 
Cuando crear un documento el Id lo asigna el SDK.
