### ISSUE TITLE
No se ejecuta el Sistema en Release

### ISSUE THREAD

**Issue by elmasfreg** [AndresRamos/ARSoftware.Contpaqi.Comercial#29]
Hola que tal muy buenas tardes compañeros ,trate de ejecutar la version Ejemplo en Realese y no conecta
![image](https://user-images.githubusercontent.com/42079475/151851610-c5b942a3-63cf-42ba-9365-6316f91b9f77.png)
 pero al ejecutarlo en Debug funciona perfectamente

**Comment by AndresRamos** [comment]
Esto fue porque en Release no había configurado el proyecto para se ejecute en x86. Este problema ya fue resuelto.
Los desarrollos y el Visual studio deben ejecutarse como Administrador y en x86.
