### ISSUE TITLE
Servidor RPC No Disponible

### ISSUE THREAD

**Issue by asanderjs** [AndresRamos/ARSoftware.Contpaqi.Comercial#31]
Buenas tardes,
Al momento de querer iniciar la Conexión me sale un error sobre el servidor RPC,
No se si a alguien mas le ha ocurrido o tenga alguna solución?
Gracias de antemano
![error](https://user-images.githubusercontent.com/108588093/200135485-d75ee87e-efaf-4b88-9fbf-c6f72b61eb8a.png)

**Comment by AndresRamos** [comment]
Este repositorio es para el SDK de CONTPAQi Comercial.
Podrias publicar tu issue en [el proyecto de Contabilidad](https://github.com/AndresRamos/Contpaqi.Sdk.Contabilidad)?

**Comment by AndresRamos** [comment]
Puedo ver que ya lo creaste https://github.com/AndresRamos/Contpaqi.Sdk.Contabilidad/issues/1
Ahi te respondi.
