### ISSUE TITLE
Problemas para obtener algunos datos

### ISSUE THREAD

**Issue by asanderjs** [AndresRamos/ARSoftware.Contpaqi.Comercial#33]
Buenas.

Como dice el titulo, tengo algunos problemas para conseguir ciertos datos, por ejemplo el id de moneda y el tipo de cambio de los documentos, como tambien la cantidad de un movimiento, entre otras cosas.

No tendria una lista de como se llaman esos datos o algo asi?

Ejemplo para la cantidad de movimiento: fLeeDatoMovimiento("CCantidad", CantidadBd, 3000).TirarSiEsError();

Una disculpa si la pregunta es muy simple, como podra notar no soy una persona muy lista :"v

Gracias de antemano

**Comment by pstoneTI** [comment]
Buen día

En la ruta donde se encuentra instalado Contpaqi Comercial encuentras una carpeta de ayuda con PDFs de varios temas, ahí está precisamente la estructura de la Base de datos:

Si no cambiaste la ruta, estaría ahí "C:\Program Files (x86)\Compac\COMERCIAL\Ayuda\COM_BDD.pdf"

Saludos

**Comment by AndresRamos** [comment]
En el Wiki en la pagina [Introduccion](https://github.com/AndresRamos/ARSoftware.Contpaqi.Comercial/wiki/Introduccion) puedes encontrar la seccion [Donde puedo encontrar documentación?](https://github.com/AndresRamos/ARSoftware.Contpaqi.Comercial/wiki/Introduccion#donde-puedo-encontrar-documentaci%C3%B3n).

Puedes encontrar los [esquemas de las bases de datos](https://github.com/AndresRamos/ARSoftware.Contpaqi.Comercial/tree/master/docs)

Te recomiendo ver como [leer datos de movimientos](https://github.com/AndresRamos/ARSoftware.Contpaqi.Comercial/wiki/Movimientos#leer-datos-del-movimientos) que también puedes encontrar en el wiki.
