### ISSUE TITLE
Paquete Nuget

### ISSUE THREAD

**Issue by victorsg60** [AndresRamos/ARSoftware.Contpaqi.Comercial#72]
Buenas tardes.
He estado iniciando en esto de Contpaqi Factura Electrónica para poder manejarlo desde mi sistema.
Al principio mi desarrollo estaba en 'NETFramework,Version=4' y no conseguía instalar el paquete Nuget 'ARSoftware.Contpaqi.Comercial.Sdk 4.4.0'. 
Subí mi proyecto a NETFramework,Version=4.6.1 y LISTO pude instalarlo.

Ahora veo que publicaron la nueva Version 'ARSoftware.Contpaqi.Comercial.Sdk 5.0.0' pero no hay forma de instalarlo

Que estoy haciendo mal?

Gracias por su atención

PD
Desarrollo con Visual Studio 2022, VB.net

No se pudo instalar el paquete 'ARSoftware.Contpaqi.Comercial.Sdk 5.0.0'. Está intentando instalar este paquete en un proyecto que tiene '.NETFramework,Version=v4.6.1' como destino, pero el paquete no contiene referencias de ensamblado o archivos de contenido compatibles con dicho marco. Para obtener más información, póngase en contacto con el autor del paquete.

**Comment by AndresRamos** [comment]
En Visual Studio cuando instalas un paquete de NuGet con la interfaz puedes ver las dependencias del paquete y con que Framework funciona. No recuerdo en que paquete fue cuando lo pase a .Net Standard 2.0 que es compatible con .Net Framework a partir de la version 4.5.1 creo.

La version 5.0 tuvo varios Breaking Changes, puedes ver los cambios en #70 .
A partir de la version 5.0 actualice el `TargetFramework` a `net7.0`. Esto significa para utilizar este paquete debes actualizar tus aplicaciones a .NET Core para utilizar .NET 7.

Tambien cambio el licenciamiento de uso, por lo que necesitarías una licencia.

El paquete `ARSoftware.Contpaqi.Comercial.Sdk` no tuvo cambios, por lo que te recomiendo que si no tienes necesidad de actualizarte te quedes con la version 4.

**Comment by victorsg60** [comment]
Muchas gracias por la información
Saludos
