### ISSUE TITLE
Problemas con Net7.0

### ISSUE THREAD

**Issue by jmier** [AndresRamos/ARSoftware.Contpaqi.Comercial#79]
Al intentar añadir el Nuget Contpaqi.Comercial.SDK.Extras muestra una incompatibilidad con Net7 a pesar que su información dice que es compatible

**Comment by AndresRamos** [comment]
Se actualizo el `TargetFramework` a `net7.0-windows` ya que el SDK usa funciones exclusivas para Windows. Debes modificar el proyecto que consume el SDK.

```
<PropertyGroup>
	<TargetFramework>net7.0-windows</TargetFramework>
</PropertyGroup>
```

**Comment by jmier** [comment]
Gracias, Ya lo modifiqué y todo ok. Me obliga o poner mi api en windows pero no es problema para mi.
