### ISSUE TITLE
Error al intentar timbrar un documento en CONTPAQi Comercial v9.0.1

### ISSUE THREAD

**Issue by AndresRamos** [AndresRamos/ARSoftware.Contpaqi.Comercial#84]
Realizando pruebas con la nueva version de CONTPAQi Comercial Premium v9.0.1 ocurre un error a intentar timbrar un documento con la función `fEmitirDocumento`.

Mensaje de error: 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'

Este es un error que truena proceso y aplicación ya que no se puede atrapar este error.

Ya se comunicó este error a CONTPAQi. Se recomienda por el momento no actualizarse a la version 9.0.1 hasta que se resuelva este error.

**Comment by SistemasMetAs** [comment]
Buen día, Andrés

Habrá alguna novedad sobre la corrección a este error?

**Comment by AndresRamos** [comment]
Este error se resuelve instalando el Service Pack 1 de la version 9.0.1 de CONTPAQi Comercial Premium liberado el día 19/09/2023
